### ISSUE TITLE
malloc.h is not available on MacOS

### ISSUE THREAD

**Issue by fdc-viktor-luft** [terminalstatic/go-xsd-validate#8]
Please replace your dependency `malloc.h` by `stdlib.h`. Then it starts working on MacOS, too.

Here he you can see that `malloc.h` seems to be deprecated: https://stackoverflow.com/a/56463133

**Comment by terminalstatic** [comment]
In the current commit and latest tagged version there is no malloc.h, this was fixed a year ago, see [here](https://github.com/terminalstatic/go-xsd-validate/pull/7)
Could it be that you're checking out an older version?

**Comment by egamble** [comment]
Version 0.1.2 of go-xsd-validate depends on `malloc.h`, which is no longer available on MacOS.

**Comment by fdc-viktor-luft** [comment]
I'm still not very familiar with golang and it's packages, but I installed the lib 4 months ago and it was the version 0.1.2 that contained malloc.h in the libxml2.go file.

Can't it bei that something didn't work correctly when publishing the lib?

**Comment by terminalstatic** [comment]
OK I had another look and realized I obviously didn't push the v0.1.3 tag to remote (so this change was only present in master).  I used the current HEAD and tagged it with v0.1.4. Thanks you guys for the hint.

**Comment by fdc-viktor-luft** [comment]
Thank you for your fast fix and your lib. I can confirm that it works now :+1:
